# Use an official Node.js runtime as a parent image
FROM node:20.14.0-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli@18

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the local code to the container's working directory
COPY . .

# Expose the port the app runs in (Angular default port)
EXPOSE 4200

# Start the Angular application in development mode and enable live-reload
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]